{% set name = "strictyaml" %}
{% set version = "1.4.0" %}
{% set sha256 = "9f4e5814f96e17e82044a7dbbb8a0976048f2841b073e8114c2a2c025e7f81b9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - python-dateutil >=2.6.0
    - ruamel.yaml >=0.14.2

test:
  imports:
    - strictyaml
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://hitchdev.com/strictyaml/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Type-safe YAML parser and validator.
  dev_url: https://github.com/crdoconnor/strictyaml

extra:
  recipe-maintainers:
    - mcs07
